# Generated by Django 5.1 on 2024-09-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('CD', 'Disque'), ('VE', 'Vetement'), ('P', 'Posters'), ('DI', 'Divers')], default='DI', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('RK', 'Rock'), ('PP', 'Pop'), ('JZ', 'Jazz'), ('CL', 'Classical'), ('HH', 'Hip Hop'), ('IN', 'Instrumental'), ('RE', 'Reggai')], max_length=5),
        ),
    ]
