# Generated by Django 5.1 on 2024-09-04 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_description_listing_sold_listing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.band'),
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('RK', 'Rock'), ('PP', 'Pop'), ('JZ', 'Jazz'), ('CL', 'Classical'), ('HH', 'Hip Hop'), ('IN', 'Instrumental'), ('RE', 'Reggae')], max_length=5),
        ),
    ]
